# The base image to use in the build.
# This is mandatory and must be the first command in the file.
# © https://jstobigdata.com
FROM busybox:latest

# `Docker inspect` can be used to view image Labels.
LABEL version = "1.0"
LABEL author = "Bikram Kundu"

CMD ["echo", "Welcome to - Zero to Hero in Docker"]
# Now go back to the tutorial and follow the commands